### ISSUE TITLE
Project Feedback - Ziyuan Zhu

### ISSUE THREAD

**Issue by ziyuanzhu1** [enriquerf/WebTechProject#4]
Technical Issues:
- On the navigation bar, a suggestion I would give is to give color to the menu when users hover over it. A hover effect can give them a clear signal to see what's clickable. 
- In terms of font size, I would make the description smaller in "Travel Accommodations" smaller since it is a lot bigger than the main content. I would also keep the fonts consistent with each other for aesthetic purposes. 

Content Suggestions: 
- I would suggest for **Tourist Places**, I would add photos and allow the user to click on the photo. After clicking on the photo, the page will navigate to another page which will have greater detail about the places. I would also add the google maps function the professor showed us in class! 
- I would also add a navigation bar or a dedicated section of your own experiences in your own country. For example, you can add your own personal photos or videos to show the reader how fun it is to explore Honduras.

**Comment by enriquerf** [comment]
Hi Ziyuan, I thank you for your detailed peer revision and thank you for the suggestions. I took your technical advice and went ahead at fixing my website with them!
