### ISSUE TITLE
Peer Review ! 

### ISSUE THREAD

**Issue by kzhong1** [enriquerf/WebTechProject#5]
I absolutely love your website design, the color scheme and the plan for it. I assume you haven't fleshed out a couple of the pages yet, but the one's that are there like the travel accommodations is great! I'd say you could make that page more aesthetic with pictures near the table? I love the links to the specific activities/places so I think you should highlight that with some hover aspects. Also you could add a map at the top with each location pinned for website visitors. 

I'd love to see some videos and more pictures, but I honestly don't have many suggestions because it looks like you are going in a great direction and I can't wait to see where you go with this

**Comment by enriquerf** [comment]
Thank you for your feedback! I made sure to go back to my site and add some of your suggestions to my final project!
